### ISSUE TITLE
[Driver] Utilize 'lightweight transaction' behavior for create/update existence checks.

### ISSUE THREAD

**Issue by tfredrich** [tfredrich/docussandra#115]
'if exists' and 'if not exists' clauses are mentioned as 'lightweight transaction' capability in the Cassandra documentation. Can we utilize them instead of the pre-read verification on create and update for databases, tables, and documents?

**Comment by JeffreyDeYoung** [comment]
I like this idea. I'll roll with it.

**Comment by JeffreyDeYoung** [comment]
I think the performance gains here are going to be trivial at best, but logically this is probably a good idea. We can't apply this to our most frequently used tables due to Cassandra restrictions.
