### ISSUE TITLE
[Driver] Create "index" table when new index created.

### ISSUE THREAD

**Issue by tfredrich** [tfredrich/docussandra#25]
When a new "Index" object is created, create the underlying column family. This is much like when a Table is created, the underlying document table gets created (see TableRepository).

**Comment by tfredrich** [comment]
This would probably occur in the IndexRepository. BTW, deleting an index would also delete the underlying table. (TableRepository does this for Document tables).

**Comment by JeffreyDeYoung** [comment]
For the sake of naming convention: tables that actually contain the indices will be know as: "iTable(s)", and the table that contains a list of the indices that exist (sys_idx) will be known as the: "index table".

**Comment by JeffreyDeYoung** [comment]
This is likely done; will review Monday morning to confirm.
