### ISSUE TITLE
[API] /version endpoint

### ISSUE THREAD

**Issue by JeffreyDeYoung** [tfredrich/docussandra#29]
Please feel free to close if you disagree: In the past, once applications were running we have found it extremely helpful to have a /version endpoint that simply displayed the version deployed (as JSON) so we could determine what version was running in a particular environment. This is extremely useful during deployments so it can be determined if an HAProxy has switched to the new version or not.

**Comment by tfredrich** [comment]
There's a version plugin for RestExpress here: https://github.com/RestExpress/PluginExpress/tree/master/version
