### ISSUE TITLE
Should we synchronize DocumentRepository and IndexRepository CRUD operations? 

### ISSUE THREAD

**Issue by JeffreyDeYoung** [tfredrich/docussandra#38]
Should we synchronize DocumentRepository and IndexRepository CRUD operations based on the entity? This would prevent a document from being deleted or updated at the same time; it would also promote atomicy when need to query the database to get index information prior to calculating the index maintenance statements (Issues #35 and #25).

**Comment by JeffreyDeYoung** [comment]
It would probably be good to avoid this as we can't sync across deploys.

**Comment by JeffreyDeYoung** [comment]
I think I have answered my own question here. We should probably not do this, but ensure that operations are independent as much as possible.

**Comment by tfredrich** [comment]
Agreed. We need to avoid locking at all costs... Later we'll support versioning (via a version number or the update_at timestamp) to accomplish the C part of ACID.

**Comment by JeffreyDeYoung** [comment]
So the answer to my question is "no". Closing.
