### ISSUE TITLE
Paging response headers are not entirely accurate

### ISSUE THREAD

**Issue by JeffreyDeYoung** [tfredrich/docussandra#50]
-response.setCollectionResponse() does not support passing of the * value for total possible response; we should fix this to use * when -1 is passed.

-response.setCollectionResponse() does not support passing of 0 as the total response size

-response.setCollectionResponse() does not seem to like it when we pass a response size with the same value as the total possible response.

**Comment by tfredrich** [comment]
This *should* be fixed now in RestExpress 0.11.x
