### ISSUE TITLE
Jenkins (figure out testing strategy)

### ISSUE THREAD

**Issue by JeffreyDeYoung** [tfredrich/docussandra#54]
We need to determine how we want to handle Cassandra based testing with Jenkins/BuildHive/Etc.

**Comment by tfredrich** [comment]
For unit tests, we need to make it so there is no dependency on Cassandra.

**Comment by JeffreyDeYoung** [comment]
If we state that there is no dependency on Cassandra for "unit tests" that means the grand majority of our tests would have to be classified as "integration tests". This isn't really a problem if there are no objections, I just want to be clear about that.

**Comment by JeffreyDeYoung** [comment]
Also, we would probably still want to have a separate Jenkins box that could run the "integration tests".

**Comment by tfredrich** [comment]
My opinion is that most of the current tests are, in fact, "integration tests" and should not be run during the public Jenkins build. That being said, we need to create UTs that do a lot of checks via stubbing out Cassandra--checking that the intended operations are appropriate.

**Comment by tfredrich** [comment]
Maybe see: https://github.com/jsevellec/cassandra-unit/wiki

**Comment by JeffreyDeYoung** [comment]
Still working on code for cassandra-unit, but is looking very good locally; submitted question to buildhive regarding firewall issues in their server: https://cloudbees.zendesk.com/hc/en-us/requests/25801
